name: test-python-package

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: nschloe/action-cached-lfs-checkout@v1
      
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 10
        platform: x64
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          g++ \
          libz-dev \
          libbz2-dev \
          liblzma-dev \
          libstdc++-10-dev \
          ninja-build

    - uses: actions/setup-python@v6
      name: Install Python
      with:
          python-version: '3.14'

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - uses: ./.github/actions/setup-rust
      with:
        cache: true

    - name: Install the project
      run: uv sync --all-groups

  build-wheel:
    needs: build-and-test
    if: ${{ startsWith(github.ref, 'refs/tags/') || contains(github.event.head_commit.message, '[wheel]') }}
    uses: regulatory-genomics/precellar/.github/workflows/wheels.yml@main

  publish:
    needs: build-wheel
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    steps:
    - name: Download wheel files
      uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: precellar-*
        merge-multiple: true

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
